"""empty message

Revision ID: 7fbdc0e0316
Revises: 1a8e36903c73
Create Date: 2016-04-17 10:23:21.953824

"""

# revision identifiers, used by Alembic.
revision = '7fbdc0e0316'
down_revision = '1a8e36903c73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###
